### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by SecularSteve** [nukeop/zeus#18]
It seems like a waste to abandon a nearly perfect attempt to recreate those **brick-games** on a virtual fantasy console.

Especially if it's easy to program your own games.

**Comment by nukeop** [comment]
I implemented most of the spec so the project is nearly "complete". The frontend, buttons, and sounds could be improved. I could never find a good way to synhesize the beeps and melodies. If it picks up interest of more people than just myself I could get back into it.

**Comment by nukeop** [comment]
It's relatively easy to program your own games, there's a "compiler" for it: https://github.com/nukeop/zeus-compiler (it produces a binary based on a list of instructions, nothing too sophisticated). There are some examples as well: https://github.com/nukeop/zeus-compiler/tree/master/examples

**Comment by SecularSteve** [comment]
I hope you don't mind that I made a suggestion on the Libretro/RetroArch forum to feature this as a core (if possible).

https://forums.libretro.com/t/id-like-to-suggest-a-possible-new-core-i-came-across-on-github/35724

It seems like it would be a perfect fit for the front-end.

**Comment by nukeop** [comment]
That would be great although I doubt my project is notable or interesting enough. If there's more interest I'm open to developing it some more.

**Comment by SecularSteve** [comment]
Okay, have a nice day 👍
